#!/usr/bin/env python3
"""Build the TRUE occupancy grid of the arena directly from worlds/arena.sdf.

Why not use maps/map.pgm?  That file was generated by maps/generate_map.py for an
older 7x7 m arena (walls at +-3 m).  The current arena.sdf is 9x9 m (walls at
+-4.5 m) with different obstacles, so map.pgm is NOT the real world.

The lidar sits 0.23 m above the floor, so the "world as the lidar sees it" is the
horizontal slice of every obstacle at z = 0.23 m.  Obstacles shorter than that are
invisible to the lidar and are excluded; trapezoids are narrower at that height
than at their base, and that is accounted for.

Grid convention matches nav_msgs/OccupancyGrid: row 0 = lowest y, col 0 = lowest x
(i.e. NOT flipped like a PGM image).  Values: 0 free, 100 occupied.
"""
import math
import os
import xml.etree.ElementTree as ET

import numpy as np

LIDAR_Z = 0.23
RESOLUTION = 0.05
# Grid covers the arena interior plus walls (outer wall face is at 4.55).
ORIGIN = (-4.6, -4.6)
SIZE_M = 9.2


def _default_sdf():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(here, '..', 'worlds', 'arena.sdf')


def _pose(model):
    p = model.find('pose')
    vals = [float(v) for v in p.text.split()] if p is not None else [0] * 6
    return vals  # x y z roll pitch yaw


def _shapes_from_sdf(sdf_path):
    """Return list of shapes as (kind, params). Skips ground plane / lights."""
    root = ET.parse(sdf_path).getroot()
    shapes = []
    for model in root.iter('model'):
        name = model.get('name', '')
        if name == 'ground_plane':
            continue
        x, y, z, roll, _, _ = _pose(model)
        col = model.find('.//collision/geometry')
        if col is None:
            continue
        box = col.find('box')
        cyl = col.find('cylinder')
        poly = col.find('polyline')
        if box is not None:
            sx, sy, sz = [float(v) for v in box.find('size').text.split()]
            if z + sz / 2 >= LIDAR_Z and z - sz / 2 <= LIDAR_Z:
                shapes.append(('box', (x, y, sx, sy), name))
        elif cyl is not None:
            r = float(cyl.find('radius').text)
            L = float(cyl.find('length').text)
            if z - L / 2 <= LIDAR_Z <= z + L / 2:
                shapes.append(('cyl', (x, y, r), name))
        elif poly is not None:
            pts = [tuple(float(v) for v in pt.text.split()) for pt in poly.findall('point')]
            h = float(poly.find('height').text)
            # Model roll of +90deg about x: polyline-y -> world z, extrusion z -> world -y.
            # So the polyline is a vertical cross-section; the footprint seen from above
            # is x-range at height z=LIDAR_Z, extruded over world y in [y-h, y].
            if abs(roll - math.pi / 2) > 1e-2:
                raise NotImplementedError(f'{name}: only roll=pi/2 polylines supported')
            xs_at_z = _polygon_xrange_at_y(pts, LIDAR_Z - z)
            if xs_at_z is not None:
                shapes.append(('rect', (x + xs_at_z[0], x + xs_at_z[1], y - h, y), name))
    return shapes


def _polygon_xrange_at_y(pts, yq):
    """x-extent of a convex polygon at horizontal line y=yq (None if outside)."""
    xs = []
    n = len(pts)
    for i in range(n):
        (x1, y1), (x2, y2) = pts[i], pts[(i + 1) % n]
        if (y1 - yq) * (y2 - yq) <= 0 and y1 != y2:
            t = (yq - y1) / (y2 - y1)
            xs.append(x1 + t * (x2 - x1))
    return (min(xs), max(xs)) if xs else None


def build_ground_truth(sdf_path=None, resolution=RESOLUTION, origin=ORIGIN, size_m=SIZE_M):
    """Return (grid[int8 H x W, 0/100], info dict with resolution & origin)."""
    sdf_path = sdf_path or _default_sdf()
    n = int(round(size_m / resolution))
    xs = origin[0] + (np.arange(n) + 0.5) * resolution
    ys = origin[1] + (np.arange(n) + 0.5) * resolution
    X, Y = np.meshgrid(xs, ys)  # shape (H, W), row = y
    occ = np.zeros((n, n), dtype=bool)
    for kind, p, _ in _shapes_from_sdf(sdf_path):
        if kind == 'box':
            cx, cy, sx, sy = p
            occ |= (np.abs(X - cx) <= sx / 2) & (np.abs(Y - cy) <= sy / 2)
        elif kind == 'cyl':
            cx, cy, r = p
            occ |= (X - cx) ** 2 + (Y - cy) ** 2 <= r ** 2
        elif kind == 'rect':
            x0, x1, y0, y1 = p
            occ |= (X >= x0) & (X <= x1) & (Y >= y0) & (Y <= y1)
    grid = np.where(occ, 100, 0).astype(np.int8)
    return grid, {'resolution': resolution, 'origin': origin}


def interior_mask(grid, info, inner_half=4.45):
    """Cells strictly inside the arena walls (where exploration is meaningful)."""
    n = grid.shape[0]
    res, ox = info['resolution'], info['origin'][0]
    c = ox + (np.arange(n) + 0.5) * res
    inside = np.abs(c) <= inner_half
    return np.outer(inside, inside)


if __name__ == '__main__':
    g, info = build_ground_truth()
    print('shape', g.shape, 'occupied cells', int((g == 100).sum()))
    try:
        from PIL import Image
        Image.fromarray(np.where(g[::-1] == 100, 0, 254).astype(np.uint8)).save('ground_truth.png')
        print('wrote ground_truth.png')
    except ImportError:
        pass
